#!/usr/bin/node

'use strict';

// Initialize CoffeeScript
require('coffee-script').register();

var Songdown = require('./lib/songdown');

var join = require('path').join;

var job = new Songdown({
    inputDir: join(__dirname, 'songs'),
    outputDir: join(__dirname, 'site')
});

job.run();
