#!/usr/bin/node

'use strict';

// Initialize CoffeeScript
require('coffee-script').register();

var Songdown = require('./lib/songdown');

var join = require('path').join;

var job = new Songdown({
    input_dir: join(__dirname, 'songs'),
    output_dir: join(__dirname, 'output')
});

job.run();
